pub fn code() {
    // cargo
    println!("**** CARGO ****",);
    /* cargo is automation for rust package
    used for building package
    retreving dependencies
    like pip or conda or npm
    and more
    */
    println!("**** CARGO.TOML ****",);
    /* package information
    requirement.txt file
    Toms obvious minimal language
    version : breaking changes. adding functionality. bug fixing => 3.2.1 semantic versioning, semver.org
    latest edition is 2018 default is 2015
    documentation
    include exclude
    publish ...
    cargo/reference/manifest.html
    dependencies checked from crates.io
    > rand = "0.7.1"
    > versions can be with regex and greater or less than sign
    > git can be used
    > local path also can help
    dev-dependencies is for test and not in final product
    */
    println!("**** CARGO.lock ****",);
    /*
    Detailed info about dependencies
    main.rs must have this in source control
    lib.rs must exclude it
    its autogenerated dont mess with it
    */
}

/*
OUTPUT
**** CARGO ****
**** CARGO.TOML ****
**** CARGO.lock ****
*/
