[package]
name = "b_b_secret_number"
version = "0.1.0"
authors = ["rahul.damani"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.7.2"